# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

name: Afrodeals pnpm workflow
on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'main' || 'dev' }}
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      fail-fast: false
      matrix:
        # Using too much GitHub Actions free usage per month...
        # node-version: [14.x, 15.x, 16.x, 17.x, 18.x]
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Setup environment variables
      env:
        PUBLIC_SNIPCART_API_KEY: ${{ secrets.PUBLIC_SNIPCART_API_KEY }}
      run: |
        cd packages/playground
        touch .env
        echo PUBLIC_SNIPCART_API_KEY="$PUBLIC_SNIPCART_API_KEY" >> .env
    - name: Install dependencies
      run: pnpm -r install
    - name: Build
      run: pnpm -r build
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: page
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main